name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to Hugging Face Space
        env:
          HF_GITHUB_SYNC_TOKEN: ${{ secrets.HF_GITHUB_SYNC_TOKEN }}
        run: |
          git remote add hf https://superdjb:${HF_GITHUB_SYNC_TOKEN}@huggingface.co/spaces/superdjb/LocoVault
          git push --force hf main
